### ISSUE TITLE
SQLAlchemy TransactionRollbackError during run_update

### ISSUE THREAD

**Issue by tmaybe** [codeforamerica/cfapi#180]
Andrew noticed the weird error below during a run_update on production. Figure out what happened, how to reproduce, how to fix.

```
Traceback (most recent call last):
  File "run_update.py", line 902, in <module>
    main(org_name=org_name, org_sources=ORG_SOURCES)
  File "run_update.py", line 871, in main
    db.session.query(Event).filter(Event.keep == False).delete()
...
sqlalchemy.exc.DBAPIError: (TransactionRollbackError) deadlock detected
DETAIL:  Process 28314 waits for ShareLock on transaction 950340; blocked by process 28427.
Process 28427 waits for ShareLock on transaction 950339; blocked by process 28314.
HINT:  See server log for query details.
 'DELETE FROM event WHERE event.keep = false' {}
```

**Comment by tmaybe** [comment]
I moved this to the backlog milestone because it's hard to reproduce and our recent changes to the database flush/commit flow may've inadvertently fixed it. Will keep an eye out for it happening again and investigate more fully with access to the Postgres logs.
