### ISSUE TITLE
A changed Meetup url breaks attendance gathering

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/cfapi#242]
#### Description
Many groups have changed their Meetup url since they added the original one to the [Brigade Information](https://docs.google.com/spreadsheets/d/1cFswd6i-80f7rMKJzLOcJzr1Zb7gUukPkoi_I9MAdjQ/edit#gid=0). Visiting that url will redirect to the new one, expect when accessing it through the API. This messes up our attendance gathering.

This is the error we get when that happens:
```
Traceback (most recent call last):
  File "get_meetup_attendance.py", line 235, in <module>
    attendee = cfapiclient.format_attendee(cfapi_org, event, attendee)
  File "get_meetup_attendance.py", line 193, in format_attendee
    "cfapi_url" : cfapi_org["url"]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

#### To Fix
We should either:
*  figure out how to redirect on the api
* notify someone to update the `events_url` on the [Brigade Information](https://docs.google.com/spreadsheets/d/1cFswd6i-80f7rMKJzLOcJzr1Zb7gUukPkoi_I9MAdjQ/edit#gid=0)

**Comment by ondrae** [comment]
We're not going to use this code anymore. https://github.com/codeforamerica/cfapi/issues/243
