### ISSUE TITLE
error in run_update.py process

### ISSUE THREAD

**Issue by tdooner** [codeforamerica/cfapi#333]
TODO: fix this

When running `heroku run python run_update.py --name "Code for Fort Collins"`

```
Traceback (most recent call last):
  File "run_update.py", line 1403, in <module>
    main(org_name=org_name, org_sources=org_sources)
  File "run_update.py", line 1333, in main
    save_labels_info(db.session, issue_dict)
  File "run_update.py", line 1122, in save_labels_info
    new_label = Label(**label_dict)
TypeError: __init__() got an unexpected keyword argument 'node_id'
Sentry is attempting to send 1 pending error messages
```

**Comment by tdooner** [comment]
cc @davidbhayes
